# Generated by Django 2.2.7 on 2021-07-05 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_ratings', '0002_auto_20210503_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 12, 56, 9, 812025)),
        ),
    ]
