# Generated by Django 2.2.7 on 2020-05-04 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_ratings', '0003_auto_20200503_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 17, 12, 9, 172421)),
        ),
    ]
