# Generated by Django 2.2.7 on 2020-05-09 14:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_listing_comment'),
        ('reviews_ratings', '0005_auto_20200504_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(null=True,blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='listings.Listing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 16, 19, 52, 724257)),
        ),
    ]
