# Generated by Django 2.2.7 on 2020-02-25 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20200225_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('wifi', models.BooleanField(default='Not available')),
                ('room_type', models.CharField(max_length=200)),
                ('bedroom', models.IntegerField(default=1)),
                ('bathroom', models.IntegerField(default=1)),
                ('garage', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/&d')),
                ('photo_1', models.ImageField(upload_to='photos/%Y/%m/&d')),
                ('photo_2', models.ImageField(upload_to='photos/%Y/%m/&d')),
                ('photo_3', models.ImageField(upload_to='photos/%Y/%m/&d')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/&d')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/&d')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/&d')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Landlord')),
            ],
        ),
    ]
