# Generated by Django 2.2.7 on 2020-02-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='wifi',
            field=models.BooleanField(default='N/A', null=True),
        ),
    ]
