# Generated by Django 2.2.7 on 2020-02-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200225_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Landlord'),
        ),
    ]
