# Generated by Django 2.2.7 on 2020-02-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200225_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='wifi',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
