# Generated by Django 2.2.7 on 2020-05-04 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200304_1508'),
        ('listings', '0007_listing_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Tenant'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='comment',
            field=models.ForeignKey(null=True,blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reviews_ratings.Comment'),
            preserve_default=False,
        ),
    ]
