# Generated by Django 2.2.7 on 2020-05-09 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20200504_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Listing', to='reviews_ratings.Comment'),
            preserve_default=False,
        ),
    ]
