# Generated by Django 2.2.7 on 2020-05-20 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200519_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='phone',
            field=models.CharField(null=False,blank=False, max_length=200),
            preserve_default=False,
        ),
    ]
