# Generated by Django 2.2.7 on 2020-05-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200520_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
