# Generated by Django 2.2.7 on 2020-06-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200520_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='photo_landlord',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/&d'),
        ),
    ]
